[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.17.0"

[[constraint]]
  name = "github.com/google/uuid"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.13.2"
